apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    secureJsonData:
      token: my-token
    jsonData:
      version: Flux
      organization: monelec
      defaultBucket: electricite
